# Generated by Django 5.1.6 on 2025-02-09 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderorm',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
